version: '3.8'

services:

  # currently we are using the MySQLite2 database
  # db:
  #   image: postgres:13
  #   environment:
  #     POSTGRES_DB: mydatabase
  #     POSTGRES_USER: myuser
  #     POSTGRES_PASSWORD: mypassword
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - rapifuzz

networks:
  rapifuzz:
    driver: bridge